name: vibee
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  # chewie: ^1.7.0
  # video_player: ^2.7.0
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^5.2.1+1
  file_picker: ^5.3.2

  flutter_bloc: ^8.1.3
  flutter_pin_code_fields: ^2.2.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  http: ^1.0.0
  http_parser: ^4.0.2
  image_picker: ^0.8.9
  json_annotation: ^4.8.1
  permission_handler: ^10.4.3
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.1.1
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  agora_uikit: ^1.3.4
  awesome_notifications: ^0.7.4+1


  

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "path/to/image.png"

flutter:
  uses-material-design: true
  fonts:
    - family: AutumnInNovember
      fonts:
        - asset: assets/fonts/Autumn in November.ttf
  assets:
    - assets/images/
    - assets/icons/
