name: vibee
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_pin_code_fields: ^2.2.0
  http: ^1.0.0
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: AutumnInNovember
      fonts:
        - asset: assets/fonts/Autumn in November.ttf
  assets:
    - assets/images/
    - assets/icons/
