name: vibee
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.2.1+1
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_pin_code_fields: ^2.2.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  http: ^1.0.0
  http_parser: ^4.0.2
  image_picker: ^0.8.9
  json_annotation: ^4.8.1
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  fonts:
    - family: AutumnInNovember
      fonts:
        - asset: assets/fonts/Autumn in November.ttf
  assets:
    - assets/images/
    - assets/icons/
